//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_DataMaskingScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditQuestionnaireAttachment
    {
        public System.Guid Id { get; set; }
        public System.Guid AuditId { get; set; }
        public System.Guid AuditQuestionnaireId { get; set; }
        public string ItemTypeCode { get; set; }
        public System.Guid QuestionnaireItemID { get; set; }
        public System.Guid AttachmentId { get; set; }
        public string AttachmentType { get; set; }
        public string FileName { get; set; }
        public System.Guid Uploader { get; set; }
        public System.DateTime UploadTime { get; set; }
        public int RecordStatus { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<System.Guid> LastUpdateUser { get; set; }
        public string Description { get; set; }
    }
}
