//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_DataMaskingScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audit()
        {
            this.AuditContacts = new HashSet<AuditContact>();
            this.AuditFacilities = new HashSet<AuditFacility>();
            this.AuditDocuments1 = new HashSet<AuditDocument>();
        }
    
        public System.Guid Id { get; set; }
        public int RowId { get; set; }
        public string InternalAuditId { get; set; }
        public string ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string SystemName { get; set; }
        public string ExternalAuditId { get; set; }
        public string AssessmentStage { get; set; }
        public System.Guid CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string Country { get; set; }
        public System.DateTime DateRangeStart { get; set; }
        public System.DateTime DateRangeEnd { get; set; }
        public Nullable<System.DateTime> DateToBeComplete { get; set; }
        public string ReAuditNumber { get; set; }
        public string MonitoringFirm { get; set; }
        public string AuditStatusCode { get; set; }
        public string AuditMainType { get; set; }
        public string ReportLanguageCode { get; set; }
        public string AuditToolLanguageCode { get; set; }
        public string AssessmentType { get; set; }
        public string OnlineOrOffLine { get; set; }
        public string FirstReviewOffice { get; set; }
        public string SecondReviewOffice { get; set; }
        public int RecordStatus { get; set; }
        public string AuditSubType { get; set; }
        public Nullable<bool> SecondReviewRequired { get; set; }
        public Nullable<int> QuietPeriod { get; set; }
        public string UnlockCode { get; set; }
        public Nullable<System.Guid> FirstReviewer { get; set; }
        public Nullable<System.Guid> SecondReviewer { get; set; }
        public string ReferenceExternalAuditId { get; set; }
        public string AuditComment { get; set; }
        public Nullable<System.DateTime> AuditCompleteDate { get; set; }
        public Nullable<int> BusinessLine { get; set; }
        public string AuditProgram { get; set; }
        public string InternalStatusInfo { get; set; }
        public bool IsPrimaryAudit { get; set; }
        public string AuditDocuments { get; set; }
        public string ReferencedPreviousSystem { get; set; }
        public System.Guid LastUpdateUser { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> IsUnlocked { get; set; }
        public string LastDownloadInfo { get; set; }
        public Nullable<bool> OriginalSecondReviewRequired { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<int> ResetVersion { get; set; }
        public string ClientName { get; set; }
        public int IsFullAccessDenied { get; set; }
        public bool SAQPrePopulationRequired { get; set; }
        public bool IsRemoteAudit { get; set; }
        public bool IsDeskTopReview { get; set; }
        public int Report_Branding { get; set; }
        public bool StageData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditContact> AuditContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditFacility> AuditFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDocument> AuditDocuments1 { get; set; }
    }
}
