//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_DataMaskingScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditFacility
    {
        public System.Guid Id { get; set; }
        public int RowId { get; set; }
        public System.Guid AuditId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<System.Guid> FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Location { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string ContactInfo { get; set; }
        public string Email { get; set; }
        public string IndustryKeyMainProduct { get; set; }
        public string IntertekUniqueID { get; set; }
        public string DUNSNumber { get; set; }
        public string FederalID { get; set; }
        public string LegalStatus { get; set; }
        public string GPS { get; set; }
        public string PrimarySpokenLanguage { get; set; }
        public string OtherSpokenLanguage { get; set; }
        public string PrimaryWrittenLanguage { get; set; }
        public string OtherWrittenLanguage { get; set; }
        public string ProductionMonths { get; set; }
        public string BusinessHours { get; set; }
        public string OfficeEmployees { get; set; }
        public string Workers { get; set; }
        public string Buildings { get; set; }
        public string Shifts { get; set; }
        public string FacilitySize { get; set; }
        public string PeakSeason { get; set; }
        public string ShiftInformation { get; set; }
        public string ProductionHours { get; set; }
        public int RecordStatus { get; set; }
        public bool IsPrimarySite { get; set; }
        public string ProductionLines { get; set; }
        public System.DateTime DateRangeStart { get; set; }
        public System.DateTime DateRangeEnd { get; set; }
        public string City { get; set; }
        public System.Guid LastUpdateUser { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string ExternalVendorId { get; set; }
        public string Zip { get; set; }
    
        public virtual Audit Audit { get; set; }
    }
}
