//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_DataMaskingScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMARTEntities : DbContext
    {
        public SMARTEntities()
            : base("name=SMARTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditContact> AuditContacts { get; set; }
        public virtual DbSet<AuditDocument> AuditDocuments { get; set; }
        public virtual DbSet<AuditFacility> AuditFacilities { get; set; }
        public virtual DbSet<AuditQuestionnaireAttachment> AuditQuestionnaireAttachments { get; set; }
        public virtual DbSet<DictionaryData> DictionaryDatas { get; set; }
        public virtual DbSet<DictionaryType> DictionaryTypes { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<TaskDataMaskingQueue> TaskDataMaskingQueues { get; set; }
    }
}
