//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART_DataMaskingScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDataMaskingQueue
    {
        public int Id { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public string System { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool IsMasked { get; set; }
        public bool IsRead { get; set; }
        public string Result { get; set; }
        public Nullable<int> LogId { get; set; }
    }
}
